### ISSUE TITLE
Update plugin to also show partial matches

### ISSUE THREAD

**Issue by edisinovcic** [sourcifyeth/remix-sourcify#27]
Contract fetcher needs to be updated to also show partial matches.

**Comment by Jakic007** [comment]
Contract verifier should also show partial match and redirect to the https://contractrepo.komputing.org/partial_matches/:id/:address
when plugin receives "status":"partial".
Right now it navigates to https://contractrepo.komputing.org/contracts/:id/:address which results in error 404.

**Comment by edisinovcic** [comment]
@FabijanC can you confirm that this is working?

**Comment by FabijanC** [comment]
There is a pending pull request (on the Sourcify repo) that introduces two new server endpoints that return partial if full is not available: https://github.com/ethereum/sourcify/pull/325

**Comment by ogwurujohnson** [comment]
@kuzdogan i think we can close this right? Since this has been implemented

**Comment by kuzdogan** [comment]
Yes sure
