### ISSUE TITLE
probable performance issue when autocompile is on

### ISSUE THREAD

**Issue by yann300** [sourcifyeth/remix-sourcify#39]
When autocompile is on:
 - activate sourcify
 - keep pressing space in the editor for triggering a compilation
 - after some time the browser become unresponsive.

This happen with Firefox

**Comment by edisinovcic** [comment]
It can be reproduced. As you mentioned probable reason is that sourcify is listening on ```compilationFinished``` and it freezes the browser. Open for proposals for solution of this.

**Comment by yann300** [comment]
This is still happening,
for reproducing:
 - activate the sourcify plugin
 - compile any contract (ctrl-s)
 - recompile it several times (ctrl-s)
 - the browser starts to freeze

Part of the issue is that the `VerifyContract` https://github.com/sourcifyeth/remix-sourcify/blob/1879b24a76be3e9bfd4034f5e402f2e3908e745b/src/components/verify-contract/VerifyContract.tsx#L62 is called after each `compilationFinished` event, which then seems to re-register using ` remixClient.listenOnCompilationFinishedEvent`

**Comment by edisinovcic** [comment]
This should be fixed now. Closing.
