### ISSUE TITLE
Select Contract to Verify inside plugin

### ISSUE THREAD

**Issue by Clearwood** [sourcifyeth/remix-sourcify#59]
Currently there is no option to select one of multiple contracts inside a flattened file.
It would be great if there was a selector.

**Comment by stebansaa** [comment]
I have a somehow related problem while trying to verify Uniswap V2 Factory contract,  Sourcify selects the wrong contract to verify and there is no option to switch it.

**Comment by kuzdogan** [comment]
Thanks, good point that seemingly is long overdue. We'll look into this

**Comment by marcocastignoli** [comment]
implemented contract selector with https://github.com/sourcifyeth/remix-sourcify/commit/ab1a7a8a04a0ac5b2bd71b3febca8b6ed346c5b1
