### ISSUE TITLE
Sourcify button under "Featured Plugins" not working

### ISSUE THREAD

**Issue by kuzdogan** [sourcifyeth/remix-sourcify#61]
![image](https://user-images.githubusercontent.com/13069972/147925824-b7a67400-1ea9-4da0-977d-0038502a54ab.png)

Clicking on the Sourcify logo here under "Featured Plugins" does not open the plugin. Likely because of the plugin name change.

**Comment by ogwurujohnson** [comment]
Fixed

**Comment by ogwurujohnson** [comment]
Fixed
