### ISSUE TITLE
Sourcify plugin icon "active" state color in dark themes

### ISSUE THREAD

**Issue by kuzdogan** [sourcifyeth/remix-sourcify#62]
Sourcify active
![image](https://user-images.githubusercontent.com/13069972/147926035-b888b7bd-2fd2-40e6-a817-d1ccbccb754f.png)

Other plugin active
![image](https://user-images.githubusercontent.com/13069972/147926103-cf6e94de-1548-4323-b48c-5e8d787d60ea.png)

The icon when the plugin is active becomes transparent in dark themes. The icon should be white as other plugins.

**Comment by ogwurujohnson** [comment]
We might need a new icon for this, the current icons we have fail on remix when we apply the icon styles.

**Comment by kuzdogan** [comment]
Hmm, why is this the case? It should be possible to modify the icon color by changing the `fill` or overlaying black or white. How do the other icons change color?

**Comment by ogwurujohnson** [comment]
When inactive the icons have a `filter: invert(0.5)` style applied, when clicked on it has a style similar to `filter: invert(1)` applied to it.

**Comment by ogwurujohnson** [comment]
Applying this styles on the images we have on the assets folder against a background similar to dark mode on remix, gives an icon that either doesnt fit the styles or looks different. Can show you on a call too if get the time.

**Comment by kuzdogan** [comment]
Maybe we can use the .svg icon in assets. Otherwise feel free to add another icon if needed.

**Comment by ogwurujohnson** [comment]
Fixed
