### ISSUE TITLE
double nav bar and overflowing box

### ISSUE THREAD

**Issue by ryestew** [sourcifyeth/remix-sourcify#69]
I went to the open zeppelin wizard got an erc20 contract and opened it up in Remix and tried to verifify it with sourcify and I got a double nav bar with overflowing text:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/6050001/169187318-a05cdf04-af6f-4a51-9850-d763ad352307.png">

**Comment by kuzdogan** [comment]
Fixed with https://github.com/sourcifyeth/remix-sourcify/commit/ca0d99e28b1dfcb6d04b48e33e3d93eb398591ae
